apiVersion: v1
kind: ConfigMap
metadata:
  name: ng-auth-ui
data:
  API_URL: http://{{ .Values.public_ip }}:{{ .Values.listen_port }}
  DEPLOYMENT_TYPE: COMMUNITY

---

apiVersion: v1
kind: Service
metadata:
  name: ng-auth-ui
  labels:
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ng-auth-ui

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-auth-ui
  labels:
    app: ng-auth-ui
spec:
  selector:
    matchLabels:
      app: ng-auth-ui
  template:
    metadata:
      labels:
        app: ng-auth-ui
    spec:
      serviceAccountName: harness-default
      containers:
      - name: ng-auth-ui
        image: harness/ng-auth-ui-signed:{{ .Values.versions.ng_auth_ui }}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 101
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /health
            port: ng-auth-ui-port
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: ng-auth-ui-port
          initialDelaySeconds: 90
          periodSeconds: 20
          failureThreshold: 2
        ports:
        - name: ng-auth-ui-port
          containerPort: 8080
          protocol: "TCP"
        envFrom:
        - configMapRef:
            name: ng-auth-ui
