apiVersion: v1
kind: Service
metadata:
  name: scm
spec:
  ports:
  - name: scm
    port: 8091
  selector:
    app: scm

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm
spec:
  selector:
    matchLabels:
      app: scm
  template:
    metadata:
      labels:
        app: scm
    spec:
      serviceAccountName: harness-default
      containers:
      - name: scm
        image: harness/ci-scm-signed:{{ .Values.versions.scm }}
        securityContext:
          runAsUser: 65534
          runAsNonRoot: true
        ports:
        - name: scm
          containerPort: 8091
          protocol: TCP
        readinessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:8091"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:8091"]
          initialDelaySeconds: 10
        resources:
          limits:
            memory: 96Mi
            cpu: 200m
          requests:
            memory: 96Mi
            cpu: 200m
